CREATE TABLE [dbo].[Adresse]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	Numero INT NOT NULL,
	Rue VARCHAR(255) NOT NULL,
	CodePostal INT NOT NULL,
	Localite VARCHAR(100) NOT NULL,
	Pays VARCHAR(100) NOT NULL,
)
